# Generated by Django 4.0.4 on 2022-05-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFunctionality', '0003_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(),
        ),
    ]
