# Generated by Django 4.0.4 on 2022-05-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFunctionality', '0004_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a product'),
        ),
    ]
