# Generated by Django 4.0.4 on 2022-05-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFunctionality', '0008_alter_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sports Wear'), ('OW', 'Outwear')], default='S', max_length=2),
        ),
    ]
