# Generated by Django 4.0.4 on 2022-05-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFunctionality', '0009_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_Url',
            field=models.TextField(default='https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg'),
        ),
    ]
