# Generated by Django 4.0.4 on 2022-05-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFunctionality', '0010_item_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sports Wear'), ('J', 'Jacket'), ('P', 'Pants')], default='S', max_length=2),
        ),
    ]
